workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable $FLUTTER_ROOT
          export PATH="$FLUTTER_ROOT/bin:$PATH"
      - name: Install Dependencies
        script: |
          flutter pub get
          cd ios
          pod install --verbose
    artifacts:
      - build/ios/ipa/**/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
