workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        IOS_DEPLOYMENT_TARGET: "13.0"
    scripts:
      - name: Set iOS Deployment Target
        script: |
          echo "Updating iOS Deployment Target to 13.0"
          cd ios
          echo "Updating Podfile..."
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/g' Podfile
          echo "Updating Xcode project..."
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' Runner.xcodeproj/project.pbxproj

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Build iOS app
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release archive -archivePath build/Runner.xcarchive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath build
