name: in_pocket
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: "none"

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  cloud_firestore: ^5.6.2
  country_picker: ^2.0.27
  country_picker_flutter: ^1.1.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_country_selector: ^1.0.14
  flutter_datetime_picker_plus: ^2.2.0
  flutter_facebook_auth: ^7.1.1
  flutter_localizations:
    sdk: flutter
  flutter_picker_plus: ^1.3.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  meta: ^1.15.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.4.0
  sign_in_with_apple: ^6.1.4
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.5.1

flutter:
  # Include material design icons
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/

  # Fonts configuration
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  # You can configure other options if needed (e.g., output paths).

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  classname: AppImages
