name: in_pocket
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: "none"

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  meta: ^1.15.0
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.5.1

flutter:
  # Include material design icons
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/

  # Fonts configuration
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  # You can configure other options if needed (e.g., output paths).

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  classname: AppImages
