// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR8wNL9Cak9dC7R2Iaj4gKCfMj4g_QcLc',
    appId: '1:198164528317:web:d976b8b2a3dacbd5648bd4',
    messagingSenderId: '198164528317',
    projectId: 'inpocket-bb64c',
    authDomain: 'inpocket-bb64c.firebaseapp.com',
    storageBucket: 'inpocket-bb64c.firebasestorage.app',
    measurementId: 'G-CSLJKQ383Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_EJmnu_0EEoo4vSVufVt--q1ApZX0PE',
    appId: '1:198164528317:android:fc7d4eb7db20e288648bd4',
    messagingSenderId: '198164528317',
    projectId: 'inpocket-bb64c',
    storageBucket: 'inpocket-bb64c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIR5KSAkbNfMb832_JXgN9k9azvwmL6MI',
    appId: '1:198164528317:ios:7668bf296ac5b697648bd4',
    messagingSenderId: '198164528317',
    projectId: 'inpocket-bb64c',
    storageBucket: 'inpocket-bb64c.firebasestorage.app',
    androidClientId: '198164528317-i8j967p7ldiq965v5foo5q5u4vb3jpfk.apps.googleusercontent.com',
    iosClientId: '198164528317-cbtbd135246cdks6bcg2js5no8qc998d.apps.googleusercontent.com',
    iosBundleId: 'com.example.deals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIR5KSAkbNfMb832_JXgN9k9azvwmL6MI',
    appId: '1:198164528317:ios:7668bf296ac5b697648bd4',
    messagingSenderId: '198164528317',
    projectId: 'inpocket-bb64c',
    storageBucket: 'inpocket-bb64c.firebasestorage.app',
    androidClientId: '198164528317-i8j967p7ldiq965v5foo5q5u4vb3jpfk.apps.googleusercontent.com',
    iosClientId: '198164528317-cbtbd135246cdks6bcg2js5no8qc998d.apps.googleusercontent.com',
    iosBundleId: 'com.example.deals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR8wNL9Cak9dC7R2Iaj4gKCfMj4g_QcLc',
    appId: '1:198164528317:web:071cfd5bbcf6868c648bd4',
    messagingSenderId: '198164528317',
    projectId: 'inpocket-bb64c',
    authDomain: 'inpocket-bb64c.firebaseapp.com',
    storageBucket: 'inpocket-bb64c.firebasestorage.app',
    measurementId: 'G-F3YCQFMXPM',
  );

}