platform :ios, '13.0'

# CocoaPods analytics disabled
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Explicitly define the Flutter root path
flutter_root = File.expand_path('..', File.dirname(__FILE__)) + '/Flutter'

# Load Flutter
load File.join(flutter_root, 'generated.xcconfig') if File.exist?(File.join(flutter_root, 'generated.xcconfig'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Include all Flutter plugins
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
