# This is the Podfile for your Flutter iOS project
platform :ios, '13.0'

# CocoaPods analytics disabled
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Flutter installation
flutter_root = File.expand_path('../flutter', __dir__)
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'pod_helper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
